### ISSUE TITLE
Fix for authentication, couldn't submit pull request

### ISSUE THREAD

**Issue by MagaliDB** [sander1988/pyIndego#111]
In my forked repository I've made some changes that will fix the authentication problem, causing the 429 error. I couldn't figure out how to do a pull request with my forked repository so here's the link to the changes: https://github.com/MagaliDB/pyIndego/commit/727a84351fff789475af81e6b3550dfdc3a62686#diff-0c4125230cc1e7a3510468d5e0a81bf7f41c46e0c2269daae49037aacf7563ad

**Comment by jm-73** [comment]
I have build a new version of the python library used by the Bosch integration. Please try this change in your config/custom_components/indego/manifest.json:

"requirements": ["pyIndego==2.0.29"],

change to

"requirements": ["pyIndego==2.0.30"],

Please let me know if it works for you!

/J

**Comment by MagaliDB** [comment]
Since I'm calling a forked repository in config/custom_components/indego/manifest.json, changing the requirements won't affect my integration, but I did compare your changes to mine and they're identical, so I can confirm that this will work! Thank you for your changes, this will get rid of the 429 bug for other users.

**Comment by jm-73** [comment]
New version of component released. Should be visible in HACS shortly.
