### ISSUE TITLE
Doest work anymore: New API / Switch to Bosch Single ID

### ISSUE THREAD

**Issue by HAuser1234** [sander1988/pyIndego#116]
Hello,

the integration doesn' seem to work anymore since bosch switched to a new API. I used a packet sniffer to see that the url is now api.indego-cloud.iot.bosch-si.com
Since the login method and API changed, pyindego ist working anymore.

Is there any possibillity to bring the functionality back? @jm-73

**Comment by jm-73** [comment]
Sure! I will have time later this spring/summer (april/may). Feel free to look into the code and bring on some PRs!

**Comment by jm-73** [comment]
It works again thanks to the work of wonderful fans of the Indego and Home Assistant. Enjoy!
