### ISSUE TITLE
Git tags

### ISSUE THREAD

**Issue by mweinelt** [sander1988/pyIndego#125]
Hi, I noticed that PyPi ships a newer version and Git tags have not been added since the 3.0 release. Is this on purpose?

(Edit: created the initial issue on the wrong repo)
<del>Hi, I wonder if this project does have a license that would redistribution. I want to package it into [nixpkgs](https://github.com/nixos/nixpkgs) for use within our home-assistant package.</del>.

**Comment by sander1988** [comment]
@mweinelt - I noticed the same thing. Probably due to lack of contributors. I just asked internally about why and if we can fix this.

**Comment by sander1988** [comment]
I have gained ownership of this repo. So I was now able to fix this. I have published the latest version (v3.2.1) to pyPi.
