### ISSUE TITLE
Add Bosch Indego S+ 400 

### ISSUE THREAD

**Issue by jarlesb** [sander1988/pyIndego#41]
Hi,

could you add Bosch Indego S+ 400 to the model list?
3600HB0103

Br,
Jarle

**Comment by jm-73** [comment]
Added in latest pyIndego. Will release a version in HACS soon!

**Comment by jarlesb** [comment]
Great and thanks!!! :)

tor. 17. okt. 2019 kl. 12:25 skrev Jens Mazzanti-Myretyr <
notifications@github.com>:
