### ISSUE TITLE
getNetwork gives error 501

### ISSUE THREAD

**Issue by jm-73** [sander1988/pyIndego#69]
The getNetwork function doesnt work. Got server error 501 Not implemented yet.
@Jumper78 could you have a look at this?

**Comment by Jumper78** [comment]
That is strange! For me the command works perfectly:
import pyIndego

IndegoApi_Instance = pyIndego.IndegoAPI(...)
IndegoApi_Instance.getNetwork()
IndegoApi_Instance.getConfig()

The two commands give the correct output and no error message.

I pulled your develop branch and it still works. Can you give a few more details?

**Comment by jm-73** [comment]
```
DEBUG:pyIndego:--- getNetwork: start
INFO:pyIndego:Call GET
DEBUG:pyIndego:      ContextID: <session_context_id>
DEBUG:pyIndego:      >>>API CALL: https://api.indego.iot.bosch-si.com:443/api/v1/alms/<serial>/network
DEBUG:pyIndego:      GET try 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.indego.iot.bosch-si.com:443
DEBUG:urllib3.connectionpool:https://api.indego.iot.bosch-si.com:443 "GET /api/v1/alms/<serial>/network HTTP/1.1" 501 0
DEBUG:pyIndego:      HTTP Status code: 501
ERROR:pyIndego:      Server answer: not implemented yet
DEBUG:pyIndego:Result = None
DEBUG:pyIndego:--- getNetwork: end
```

**Comment by jm-73** [comment]
Could you have a look at the API call above? Am I doing something wrong in the call?

**Comment by jm-73** [comment]
In release 1.7 of the HA Integration these function are included. It gives a log message stating if the mower used supports this call. Eg. the Indego 1000 does not support this API call

**Comment by Jumper78** [comment]
For me, the API call never gives the error. I am using an Indego S+ 400. Is it possible that the API call and its return values depend on the model number?

**Comment by jm-73** [comment]
I think it depends on the model. Sorry for not giving tour code any attention. But I am not able to test it as my mower dont support this commands.

The plan is to filter out wich mowers sypport this command and the ones that dont.

**Comment by Jumper78** [comment]
No worries about the code, I will try to take care about it.

If filtering out by model is the only option, we should start a table which model supports this feature:
| Indego 1000 | | no |
| Indego S+ 400 | 3600HB0106 | yes |

**Comment by jm-73** [comment]
I know that the 1000/1200 are not supported. All other users of this integration have 350/400 models. And they seem to support this.

**Comment by jm-73** [comment]
We have error handling for this now so I close this for now!
