### ISSUE TITLE
getLongpollState returns error 400

### ISSUE THREAD

**Issue by jm-73** [sander1988/pyIndego#70]
GetLongpollState gives error: "400: Bad Request" from server
@Jumper78  could you have a look at this?

**Comment by Jumper78** [comment]
calling getLongpollState before calling getState gives
- 5x "need to call login again"
- and "Tried 5 times to get data but didnt succeed"

if I call get State before, it looks better and gives "server backend did not have an update before timeout" and "None" as return

I need to have a look at this tonight

**Comment by jm-73** [comment]
The try 1 to 5 was a coding error. Fixed now in develop branch. The get calls the login function when it fails, but didnt succeed in refreshing the login token.

**Comment by jm-73** [comment]
I also got the timeout at try 1 now after 30s. Maybe I should have the call open for a longer time?

**Comment by jm-73** [comment]
Maybe it is working av planned? I got error 504. Error 504 means that the server did not have any update before the timeout.

**Comment by jm-73** [comment]
Ok, I understand. You have to run a regular getState beforde the Longpoll in order to get a value to send with the longpoll instruction. If you dont do this, then you get an 400 error (Bad Request).

**Comment by jm-73** [comment]
I pulled code to the develop branch that contains the controls before getLongpollState calls the API. If no old state = no API call.
