### ISSUE TITLE
getConfig returns 500 error

### ISSUE THREAD

**Issue by jm-73** [sander1988/pyIndego#71]
getConfig returns 500 error from server (Internal error)
@Jumper78 could you have a look at this?

**Comment by Jumper78** [comment]
That is strange! For me the command works perfectly:
import pyIndego

IndegoApi_Instance = pyIndego.IndegoAPI(...)
IndegoApi_Instance.getNetwork()
IndegoApi_Instance.getConfig()

The two commands give the correct output and no error message.

I pulled your develop branch and it still works. Can you give a few more details?

**Comment by jm-73** [comment]
```
INFO:pyIndego:Call GET
DEBUG:pyIndego:      ContextID: <my_session_context_id>
DEBUG:pyIndego:      >>>API CALL: https://api.indego.iot.bosch-si.com:443/api/v1/alms/<serial>/config
DEBUG:pyIndego:      GET try 1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.indego.iot.bosch-si.com:443
DEBUG:urllib3.connectionpool:https://api.indego.iot.bosch-si.com:443 "GET /api/v1/alms/<serial>/config HTTP/1.1" 500 14
DEBUG:pyIndego:      HTTP Status code: 500
ERROR:pyIndego:      Server answer: Internal Server Error
DEBUG:pyIndego:--- getConfig: end
```

**Comment by jm-73** [comment]
Now I have seen it with my own eyes that getConfig is working. Maybe it is mower dependent? My mower is rather old och maybe it cannot anser this call?

**Comment by jm-73** [comment]
In release 1.7 of the HA Integration these function are included. It gives a log message stating if the mower used supports this call. Eg. the Indego 1000 does not support this API call

**Comment by jm-73** [comment]
We have error handling for this now for the models that gives an error. So we close this for now.
