### ISSUE TITLE
Use with plain python - Doc for newb

### ISSUE THREAD

**Issue by stbuerger** [sander1988/pyIndego#76]
Among the not so many projects for the Bosch Indego API, I found this to be the most current, clear and complete one. Unfortunately I'm not familiar enough with Python to easily deduct how to use the API with a plain Python program - or even interactive - outside the Home Assistant environment.
Are there any docs or examples for this ?

**Comment by jm-73** [comment]
No not more than the readme. It may appear some test code when we release the 2.0 version of the pyIndego. You may have a look at the develop-branch to see the latest code.

**Comment by jm-73** [comment]
Connect to the discord channel, I could guide you there!
