### ISSUE TITLE
implicit login does not work without serial number

### ISSUE THREAD

**Issue by Jumper78** [sander1988/pyIndego#99]
I am usually not using the `login()` function and rely on that being called implicitly. If I do the following, I do get an error:
`indego = pyIndego.IndegoClient(username='xxx@xxx.xx', password='xxx')`
`indego.update_next_mow()`

The error is:
`404 Client Error:  for url: https://api.indego.iot.bosch-si.com/api/v1/alms/None/predictive/nextcutting: Failed to update Indego status.`

If I do the same with the serial number in the call of the API, I do not get an error:
`indego = pyIndego.IndegoClient(username='xxx@xxx.xx', password='xxx', serial='xxx')`
`indego.update_next_mow()`

I also do not get an error, if I call the `login()` function explicitly:
`indego = pyIndego.IndegoClient(username='xxx@xxx.xx', password='xxx')`
`Indego.login()`
`indego.update_next_mow()`

Since the README states that the serial is optional and does not mention anything about the `login()`function, this could lead to frustrated users. I see two possible fixes:
* catch the error in the `_request()` function and make it possible to implicitly call the `login()`
* give a hint in the README that the `login()` function needs to be called explicitly if the serial number is not given

@eavanvalkenburg , @jm-73 : which fix should we implement?

**Comment by eavanvalkenburg** [comment]
I think just doing a check if serial is set and then returning none with a warning when doing a request that uses serial

**Comment by eavanvalkenburg** [comment]
But good catch

**Comment by jm-73** [comment]
Fixad in release 2.0.26
